// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package classifier

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DoRequest provides a mock function for the type MockClient
func (_mock *MockClient) DoRequest(ctx context.Context, systemPrompt string, userInput string) (string, error) {
	ret := _mock.Called(ctx, systemPrompt, userInput)

	if len(ret) == 0 {
		panic("no return value specified for DoRequest")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, systemPrompt, userInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, systemPrompt, userInput)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, systemPrompt, userInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_DoRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoRequest'
type MockClient_DoRequest_Call struct {
	*mock.Call
}

// DoRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - systemPrompt string
//   - userInput string
func (_e *MockClient_Expecter) DoRequest(ctx interface{}, systemPrompt interface{}, userInput interface{}) *MockClient_DoRequest_Call {
	return &MockClient_DoRequest_Call{Call: _e.mock.On("DoRequest", ctx, systemPrompt, userInput)}
}

func (_c *MockClient_DoRequest_Call) Run(run func(ctx context.Context, systemPrompt string, userInput string)) *MockClient_DoRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_DoRequest_Call) Return(s string, err error) *MockClient_DoRequest_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClient_DoRequest_Call) RunAndReturn(run func(ctx context.Context, systemPrompt string, userInput string) (string, error)) *MockClient_DoRequest_Call {
	_c.Call.Return(run)
	return _c
}
