// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package router

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSkill creates a new instance of MockSkill. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkill(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkill {
	mock := &MockSkill{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSkill is an autogenerated mock type for the Skill type
type MockSkill struct {
	mock.Mock
}

type MockSkill_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkill) EXPECT() *MockSkill_Expecter {
	return &MockSkill_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockSkill
func (_mock *MockSkill) Execute(userInput string) (string, error) {
	ret := _mock.Called(userInput)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(userInput)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(userInput)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSkill_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSkill_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - userInput string
func (_e *MockSkill_Expecter) Execute(userInput interface{}) *MockSkill_Execute_Call {
	return &MockSkill_Execute_Call{Call: _e.mock.On("Execute", userInput)}
}

func (_c *MockSkill_Execute_Call) Run(run func(userInput string)) *MockSkill_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkill_Execute_Call) Return(s string, err error) *MockSkill_Execute_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSkill_Execute_Call) RunAndReturn(run func(userInput string) (string, error)) *MockSkill_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClassifier creates a new instance of MockClassifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClassifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClassifier {
	mock := &MockClassifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClassifier is an autogenerated mock type for the Classifier type
type MockClassifier struct {
	mock.Mock
}

type MockClassifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClassifier) EXPECT() *MockClassifier_Expecter {
	return &MockClassifier_Expecter{mock: &_m.Mock}
}

// Classify provides a mock function for the type MockClassifier
func (_mock *MockClassifier) Classify(ctx context.Context, userInput string) (string, error) {
	ret := _mock.Called(ctx, userInput)

	if len(ret) == 0 {
		panic("no return value specified for Classify")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, userInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, userInput)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClassifier_Classify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Classify'
type MockClassifier_Classify_Call struct {
	*mock.Call
}

// Classify is a helper method to define mock.On call
//   - ctx context.Context
//   - userInput string
func (_e *MockClassifier_Expecter) Classify(ctx interface{}, userInput interface{}) *MockClassifier_Classify_Call {
	return &MockClassifier_Classify_Call{Call: _e.mock.On("Classify", ctx, userInput)}
}

func (_c *MockClassifier_Classify_Call) Run(run func(ctx context.Context, userInput string)) *MockClassifier_Classify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClassifier_Classify_Call) Return(s string, err error) *MockClassifier_Classify_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClassifier_Classify_Call) RunAndReturn(run func(ctx context.Context, userInput string) (string, error)) *MockClassifier_Classify_Call {
	_c.Call.Return(run)
	return _c
}
